In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.multiclass import OneVsRestClassifier

In [3]:
cd ../src

/Users/williamferreira/Dropbox/mscproject/src


In [4]:
from model.utils import get_dataset, split_data

In [5]:
X, y = split_data(get_dataset('url-versions-2015-06-14-clean-train.csv'))

In [6]:
from model.baseline.rf_predictors import RandomForestBaselinePredictor

In [7]:
blp = RandomForestBaselinePredictor()
blp.fit(X, y)

RandomForestBaselinePredictor(criterion='gini', min_samples_leaf=2,
               n_estimators=1000, n_jobs=-1)

In [8]:
from model.baseline.transforms import RefutativeWordsTransform, SemanticRelationshipTransform, ImplicativeWordTransform

In [13]:
from model.baseline.transforms import _refutative_words, _implicative_words

In [14]:
features = [f.__name__ for f in SemanticRelationshipTransform._funcs.values()]

In [15]:
features.extend(_refutative_words)
features.append('?')
features.extend(_implicative_words)
features.append('word overlap')

In [ ]:
coef = blp.classifier.feature_importances_.T
coef.shape

In [ ]:
feature_significance = pd.DataFrame(coef)
feature_significance.columns = blp.classifier.classes_

In [ ]:
feature_significance['feature']= features

In [ ]:
significant_features = feature_significance[(feature_significance.against > 0.0) | (feature_significance['for'] > 0.0) | (feature_significance.observing > 0.0)]

In [ ]:
significant_features

In [24]:
significant_features.to_csv('../data/url-versions-2015-06-14-clean-train-significant_features.csv')

In [20]:
blp.pipeline.fit_transform(X[X.index == 407], ['for'])

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [22]:
blp.predict_proba(X[X.index == 407])

array([[ 0.11920789,  0.48432101,  0.39647111]])

In [23]:
blp.classifier.classes_

array(['against', 'for', 'observing'], dtype=object)

In [34]:
import math

In [38]:
list(map(math.exp, blp.classifier.intercept_))

[0.2571801544464253, 0.34822871511044545, 0.6463041734862076]

In [36]:
blp.classifier.intercept_scaling

1

In [14]:
blp.classifier.feature_importances_

array([ 0.10706701,  0.0166519 ,  0.0042427 ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.07896452,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.19734306,  0.        ,  0.        ,  0.        ,
        0.0015269 ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.13592805,  0.        ,  0.        ,
        0.00120985,  0.        ,  0.        ,  0.00795159,  0.02366085,
        0.00807787,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.00042601,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.00343751,  0.        ,
        0.00135097,  0.        ,  0.        ,  0.        ,  0.  