In [1]:
cd ../src

/Users/williamferreira/Dropbox/mscproject/src


In [2]:
from model.utils import get_ppdb_data

In [3]:
ppdb_data = get_ppdb_data()

In [8]:
from model.utils import get_stanparse_data

In [9]:
stanparse_data = get_stanparse_data()

In [17]:
id = stanparse_data.keys()[3]

In [19]:
from model.utils import get_stanparse_depths

In [20]:
stanparse_depths = get_stanparse_depths()

In [22]:
dep = stanparse_depths[id]
dep

{0: ({0: {3}, 3: {1, 2, 5}, 5: {7}, 7: {6, 9}, 9: {8, 10}, 10: {12}},
  {(0, 3): u'root',
   (3, 1): u'nn',
   (3, 2): u'nn',
   (3, 5): u'dep',
   (5, 7): u'rcmod',
   (7, 6): u'nsubj',
   (7, 9): u'dobj',
   (9, 8): u'nn',
   (9, 10): u'vmod',
   (10, 12): u'prep_in'},
  {0: 0, 1: 2, 2: 2, 3: 1, 5: 2, 6: 4, 7: 3, 8: 5, 9: 4, 10: 5, 12: 6})}

In [36]:
def get_word_in_sentence_at_pos(id, s_num, pos):
    stanparse_data = get_stanparse_data()
    sentence = stanparse_data[id]['sentences'][s_num]
    return sentence['words'][pos-1][1]['Lemma'].lower()

In [38]:
get_word_in_sentence_at_pos(id, 0, 7)

u'claim'

In [23]:
stanparse_data[id]

{u'sentences': [{u'dependencies': [[u'root', u'ROOT-0', u'hoax-3'],
    [u'nn', u'hoax-3', u'Banksy-1'],
    [u'nn', u'hoax-3', u'arrest-2'],
    [u'dep', u'hoax-3', u'US-5'],
    [u'nsubj', u'claims-7', u'website-6'],
    [u'rcmod', u'US-5', u'claims-7'],
    [u'nn', u'artist-9', u'street-8'],
    [u'dobj', u'claims-7', u'artist-9'],
    [u'vmod', u'artist-9', u'caught-10'],
    [u'prep_in', u'caught-10', u'Watford-12']],
   u'parsetree': u'(ROOT (NP (NP (NNP Banksy) (NN arrest) (NN hoax)) (: :) (NP (NP (NNP US)) (SBAR (S (NP (NN website)) (VP (VBZ claims) (NP (NP (NN street) (NN artist)) (VP (VBN caught) (PP (IN in) (NP (NNP Watford)))))))))))',
   u'text': u'Banksy arrest hoax: US website claims street artist caught in Watford',
   u'words': [[u'Banksy',
     {u'CharacterOffsetBegin': u'0',
      u'CharacterOffsetEnd': u'6',
      u'Lemma': u'Banksy',
      u'NamedEntityTag': u'PERSON',
      u'PartOfSpeech': u'NNP'}],
    [u'arrest',
     {u'CharacterOffsetBegin': u'7',
      u'Cha

In [39]:
ppdb_data.get('love', [])

[('loving', 3.44406, 'OtherRelated'),
 ('like', 3.22034, 'Independent'),
 ('loves', 2.97054, 'Equivalence'),
 ('beloved', 2.75429, 'ReverseEntailment'),
 ('sweet', 2.20022, 'OtherRelated'),
 ('favorite', 2.10909, 'Independent'),
 ('iove', 2.00716, 'Independent'),
 ('fond', 1.84802, 'OtherRelated'),
 ('romantic', 1.65626, 'OtherRelated'),
 ('loves', 6.26484, 'ForwardEntailment'),
 ('-love', 3.13419, 'OtherRelated'),
 ('chuckles', 2.55762, 'Independent'),
 ('romance', 2.52716, 'OtherRelated'),
 ('likes', 2.49761, 'Independent'),
 ('like', 2.49761, 'Independent'),
 ('beloved', 2.3886, 'ReverseEntailment'),
 ('loving', 2.35619, 'OtherRelated'),
 ('iove', 2.12259, 'Independent'),
 ('honey', 2.09327, 'Independent'),
 ('amour', 2.08761, 'Independent'),
 ('dear', 2.07402, 'OtherRelated'),
 ('amor', 1.97347, 'Independent'),
 ('caring', 1.91237, 'OtherRelated'),
 ("'amour", 1.79659, 'Independent'),
 ('darling', 1.7833, 'OtherRelated'),
 ('sweetheart', 1.77217, 'OtherRelated'),
 ('oi', 1.7222, 'I

In [73]:
ppdb_data['love']

[('loving', 3.44406, 'OtherRelated'),
 ('like', 3.22034, 'Independent'),
 ('loves', 2.97054, 'Equivalence'),
 ('beloved', 2.75429, 'ReverseEntailment'),
 ('sweet', 2.20022, 'OtherRelated'),
 ('favorite', 2.10909, 'Independent'),
 ('iove', 2.00716, 'Independent'),
 ('fond', 1.84802, 'OtherRelated'),
 ('romantic', 1.65626, 'OtherRelated'),
 ('loves', 6.26484, 'ForwardEntailment'),
 ('-love', 3.13419, 'OtherRelated'),
 ('chuckles', 2.55762, 'Independent'),
 ('romance', 2.52716, 'OtherRelated'),
 ('likes', 2.49761, 'Independent'),
 ('like', 2.49761, 'Independent'),
 ('beloved', 2.3886, 'ReverseEntailment'),
 ('loving', 2.35619, 'OtherRelated'),
 ('iove', 2.12259, 'Independent'),
 ('honey', 2.09327, 'Independent'),
 ('amour', 2.08761, 'Independent'),
 ('dear', 2.07402, 'OtherRelated'),
 ('amor', 1.97347, 'Independent'),
 ('caring', 1.91237, 'OtherRelated'),
 ("'amour", 1.79659, 'Independent'),
 ('darling', 1.7833, 'OtherRelated'),
 ('sweetheart', 1.77217, 'OtherRelated'),
 ('oi', 1.7222, 'I

In [74]:
entailment_set = {'ReverseEntailment', 'ForwardEntailment', 'Equivalence', 'Independent'}

In [77]:
ppdb_data = get_ppdb_data()
relationships = [(x, s, e) for (x, s, e) in ppdb_data.get('love', []) if e in entailment_set and x == 'donkey']
relationships

[]

In [55]:
max(relationships, key=lambda x: x[1])[2]

'ForwardEntailment'

In [56]:
import numpy as np

In [57]:
m = np.zeros((3, 4))
m

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [58]:
m[0, :] = np.ones((1, 4))

In [59]:
m

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [69]:
vec = np.zeros((1, 4))
vec

array([[ 0.,  0.,  0.,  0.]])

In [70]:
vec[0, 3] = 1
vec

array([[ 0.,  0.,  0.,  1.]])

In [62]:
vec

array([[ 1.,  1.,  1.,  1.]])

In [ ]:
vec 