In [1]:
cd ../src

/Users/williamferreira/Dropbox/mscproject/src


In [2]:
from model.utils import get_tokenized_lemmas

In [3]:
get_tokenized_lemmas("She didn't see the elephant")

['she', 'did', "n't", 'see', 'the', 'elephant']

In [4]:
from model.stanford import nlp

In [7]:
nlp.parse("She didn't see the elephant")

{u'sentences': [{u'dependencies': [[u'root', u'ROOT-0', u'see-4'],
    [u'nsubj', u'see-4', u'She-1'],
    [u'aux', u'see-4', u'did-2'],
    [u'neg', u'see-4', u"n't-3"],
    [u'det', u'elephant-6', u'the-5'],
    [u'dobj', u'see-4', u'elephant-6']],
   u'parsetree': u"(ROOT (S (NP (PRP She)) (VP (VBD did) (RB n't) (VP (VB see) (NP (DT the) (NN elephant))))))",
   u'text': u"She didn't see the elephant",
   u'words': [[u'She',
     {u'CharacterOffsetBegin': u'0',
      u'CharacterOffsetEnd': u'3',
      u'Lemma': u'she',
      u'NamedEntityTag': u'O',
      u'PartOfSpeech': u'PRP'}],
    [u'did',
     {u'CharacterOffsetBegin': u'4',
      u'CharacterOffsetEnd': u'7',
      u'Lemma': u'do',
      u'NamedEntityTag': u'O',
      u'PartOfSpeech': u'VBD'}],
    [u"n't",
     {u'CharacterOffsetBegin': u'7',
      u'CharacterOffsetEnd': u'10',
      u'Lemma': u'not',
      u'NamedEntityTag': u'O',
      u'PartOfSpeech': u'RB'}],
    [u'see',
     {u'CharacterOffsetBegin': u'11',
      u'Chara

In [8]:
from nltk.stem.porter import PorterStemmer

In [9]:
stemmer = PorterStemmer()

In [23]:
stemmer.stem('reportedly')

u'reportedli'

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
cv = CountVectorizer(vocabulary=['a', 'b', 'c', 'd'])

In [31]:
cv.vocabulary

['a', 'b', 'c', 'd']

In [33]:
s = set([1, 2, 3])

In [34]:
s

{1, 2, 3}

In [38]:
s.update([3, 4, 5])

In [39]:
s

{1, 2, 3, 4, 5}

In [40]:
cv = CountVectorizer()

In [42]:
cv.fit_transform(['Hello?'])

<1x1 sparse matrix of type '<type 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [43]:
cv.get_feature_names()

[u'hello']

In [12]:
s = set([1,2,3])
s.difference_update([2, 3])
s

{1}

In [2]:
import numpy as np

In [12]:
from model.utils import get_dataset, get_tokenized_lemmas
from model.baseline.transforms import _refuting_words, _hedging_words

In [13]:
df_test = get_dataset('url-versions-2015-06-14-clean-test.csv')
df_train = get_dataset('url-versions-2015-06-14-clean-train.csv')

In [17]:
hr_words = set(_refuting_words)
hr_words.update(_hedging_words)

In [19]:
all_test_words = set()
for _, row in df_test.iterrows():
    toks = get_tokenized_lemmas(row.articleHeadline)
    all_test_words.update(toks)

In [20]:
all_train_words = set()
for _, row in df_train.iterrows():
    toks = get_tokenized_lemmas(row.articleHeadline)
    all_train_words.update(toks)

In [23]:
(all_test_words.intersection(hr_words)).difference(all_train_words.intersection(hr_words))

{'refute', 'supposedly'}

In [28]:
bins = np.arange(-1.0, 1.1, 0.1)
bins

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01,   1.00000000e+00])

In [31]:
np.digitize([1.0], bins)

array([21])

In [33]:
bins.shape[0]

21

In [34]:
from model.utils import get_ppdb_data

In [35]:
ppdb_data = get_ppdb_data()

In [36]:
ppdb_data['city']

[('cities', 6.42631, 'ReverseEntailment'),
 ('town', 3.16952, 'OtherRelated'),
 ('towns', 3.16952, 'OtherRelated'),
 ('municipality', 3.11759, 'ForwardEntailment'),
 ('municipalities', 3.11759, 'ForwardEntailment'),
 ('metropolis', 2.67227, 'OtherRelated'),
 ('cit\xc3\xa9', 2.39422, 'Independent'),
 ('district', 2.31227, 'ForwardEntailment'),
 ('metropolitan', 2.22038, 'Independent'),
 ('municipal', 2.19666, 'Independent'),
 ('capital', 2.09307, 'OtherRelated'),
 ('ciudad', 2.08186, 'Independent'),
 ('urban', 2.08134, 'Independent'),
 ('ville', 2.07875, 'Independent'),
 ('precinct', 2.07006, 'Independent'),
 ('location', 2.02861, 'Independent'),
 ('jerusalem', 1.90066, 'OtherRelated'),
 ('township', 1.80446, 'OtherRelated'),
 ('cited', 1.79416, 'Independent'),
 ('shanghai', 1.79292, 'ReverseEntailment'),
 ('madinat', 1.77269, 'Independent'),
 ('downtown', 1.76181, 'OtherRelated'),
 ('medina', 1.73073, 'Independent'),
 ('community', 1.65624, 'Independent'),
 ('shing', 1.64008, 'Independ

In [37]:
_entailment_map = {
        'ReverseEntailment': 0,
        'ForwardEntailment': 1,
        'Equivalence': 2,
        'OtherRelated': 2,
    }

In [39]:
len(set(_entailment_map.values()))

3

In [40]:
arr = np.array([3, 1, 3, 2, 6])

In [42]:
np.argsort(arr)[::-1]

array([4, 2, 0, 3, 1])

In [43]:
from model.utils import get_hungarian_alignment_score_data

In [44]:
ha_data = get_hungarian_alignment_score_data()

In [47]:
ha_data[('751c5e10-c379-11e4-9435-a96703525a9e', '95b980b0-c380-11e4-9435-a96703525a9e')]

([(0, 0),
  (1, 1),
  (2, 15),
  (3, 2),
  (4, 4),
  (5, 7),
  (6, 8),
  (7, 6),
  (8, 9),
  (9, 10),
  (10, 3),
  (11, 5),
  (12, 14),
  (14, 11),
  (16, 13),
  (17, 16),
  (18, 12)],
 -0.20131411764705853)